- name: Provision Single-Node Kubernetes Cluster
  hosts: all
  become: true
  tasks:
    - name: Install required packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - containerd
        state: present
        update_cache: yes

    - name: Create /etc/apt/keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Check if Kubernetes GPG key is already installed
      stat:
        path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      register: gpg_key_status

    # Make declarative
    - name: Add Kubernetes GPG key
      become: true
      shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      args:
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      when: gpg_key_status.stat.exists == false

    - name: Change permissions of the GPG key
      become: true
      file:
        path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        owner: root
        group: root
        mode: '0644'

    - name: Add Kubernetes APT repository
      become: true
      copy:
        content: |
          deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg]  https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /
        dest: /etc/apt/sources.list.d/kubernetes.list

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install kubeadm, kubelet, and kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present

    - name: Hold the Kubernetes packages at their installed versions
      become: true
      command: apt-mark hold kubelet kubeadm kubectl

    - name: Disable swap
      shell: |
        if swapon --show | grep -q swap; then
          swapoff -a
        fi
      changed_when: false

    - name: Ensure swap is disabled on reboot
      replace:
        path: /etc/fstab
        regexp: '^(.*/swap.*)$'
        replace: '# \1'

    - name: Create /etc/containerd directory
      file:
        path: /etc/containerd
        state: directory
        mode: '0755'

    - name: Generate the default containerd config and save to file
      command: containerd config default
      register: containerd_default_config

    - name: Write containerd config to /etc/containerd/config.toml
      copy:
        content: "{{ containerd_default_config.stdout }}"
        dest: /etc/containerd/config.toml

    - name: Update SystemdCgroup to true in containerd config, for single node clusters
      lineinfile:
        backrefs: true
        path: /etc/containerd/config.toml
        regexp: '^(\s*)SystemdCgroup = false'
        line: '\1SystemdCgroup = true'

    - name: Enable and start containerd
      systemd:
        name: containerd
        enabled: true
        state: started
      become: true

    - name: Ensure overlay module is loaded
      command: modprobe overlay
      become: true

    - name: Ensure br_netfilter module is loaded
      command: modprobe br_netfilter
      become: true

    - name: Set sysctl parameters for Kubernetes networking
      sysctl:
        name: "{{ item }}"
        value: 1
        sysctl_set: yes
        state: present
        reload: yes
      with_items:
        - net.bridge.bridge-nf-call-iptables
        - net.bridge.bridge-nf-call-ip6tables
        - net.ipv4.ip_forward
      become: true

    - name: Make sysctl settings persistent
      blockinfile:
        path: /etc/sysctl.d/99-kubernetes.conf
        create: yes
        block: |
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1
      become: true

    - name: Ensure tmp kube directory exists
      file:
        path: "/tmp/kube"
        state: directory
        mode: '0755'

    - name: Check if Azure Secret exists
      stat:
        path: /tmp/kube/azure.json
      register: kube_azure_secret_check

    - name: Create Azure Secret
      copy:
        dest: "/tmp/kube/azure.json"
        content: |
          {
            "tenantId": "{{ oidc_tenant_id }}",
            "subscriptionId": "{{ azure_subscription_id }}",
            "resourceGroup": "{{ resource_group }}",
            "aadClientId": "{{ oidc_client_id }}",
            "cloud": "AzurePublicCloud",
            "oidcIssuerUrl": "https://{{ public_ip  }}/openid/v1/",
            "oidcTokenPath": "/var/run/secrets/tokens"
          }
      when: kube_azure_secret_check.stat.exists == false

    - name: Check if Api Server Cluster Configuration exists
      stat:
        path: /tmp/kube/apiserver-config.yml
      register: kube_apiserver_check

    - name: Create Kubernetes Api Server Cluster Configuration
      copy:
        dest: "/tmp/kube/apiserver-config.yml"
        content: |
          apiVersion: kubeadm.k8s.io/v1beta4
          bootstrapTokens:
            - groups:
                - system:bootstrappers:kubeadm:default-node-token
              token: 1h8mlr.fodnfo5o8fqix0x9
              ttl: 24h0m0s
              usages:
                - signing
                - authentication
          kind: InitConfiguration
          localAPIEndpoint:
            advertiseAddress: 10.0.1.4
            bindPort: 6443
          nodeRegistration:
            criSocket: unix:///var/run/containerd/containerd.sock
            imagePullPolicy: IfNotPresent
            imagePullSerial: true
            name: k8s-node-1
            taints:
              - effect: NoSchedule
                key: node-role.kubernetes.io/control-plane
          timeouts:
            controlPlaneComponentHealthCheck: 4m0s
            discovery: 5m0s
            etcdAPICall: 2m0s
            kubeletHealthCheck: 4m0s
            kubernetesAPICall: 1m0s
            tlsBootstrap: 5m0s
            upgradeManifests: 5m0s
          ---
          apiServer:
            extraArgs:
              - name: oidc-client-id
                value: "{{ oidc_client_id }}"
              - name: oidc-issuer-url
                value: https://{{ public_ip }}
              - name: oidc-username-claim
                value: sub
              - name: pod-network-cidr
                value: 192.168.0.0/16
          apiVersion: kubeadm.k8s.io/v1beta4
          caCertificateValidityPeriod: 87600h0m0s
          certificateValidityPeriod: 8760h0m0s
          certificatesDir: /etc/kubernetes/pki
          clusterName: kubernetes
          controllerManager: {}
          dns: {}
          encryptionAlgorithm: RSA-2048
          etcd:
            local:
              dataDir: /var/lib/etcd
          imageRepository: registry.k8s.io
          kind: ClusterConfiguration
          kubernetesVersion: v1.31.2
          networking:
            dnsDomain: cluster.local
            serviceSubnet: 10.96.0.0/12
          proxy: {}
          scheduler: {}
      when: kube_apiserver_check.stat.exists == false

    - name: Check if Kubernetes cluster is already initialized
      stat:
        path: /etc/kubernetes/admin.conf
      register: kubeadm_status

    - name: Initialize Kubernetes cluster
      command: kubeadm init --config /tmp/kube/apiserver-config.yml
      when: kubeadm_status.stat.exists == false
      become: true

    - name: Create .kube directory if it doesn't exist
      file:
        path: "/home/{{ ansible_user }}/.kube"
        state: directory
        mode: '0755'
      become: yes
      become_user: "{{ ansible_user }}"

    - name: Copy /etc/kubernetes/admin.conf to $HOME/.kube/config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "/home/{{ ansible_user }}/.kube/config"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'
        remote_src: yes
      become: yes

    - name: Check if Azure Secret exists
      command: kubectl get secret azure-config-secret -n kube-system
      register: kube_azure_secret_check
      failed_when: false

    - name: Apply Azure Secret
      command: kubectl create secret generic azure-config-secret --from-file=/tmp/kube/azure.json -n kube-system
      become: true
      become_user: "{{ ansible_user }}"
      when: kube_azure_secret_check.rc != 0

    - name: Check if control-plane taint is present
      shell: |
        kubectl get nodes -o jsonpath='{.items[0].spec.taints}' | grep -q "node-role.kubernetes.io/control-plane"
      register: taint_check
      become_user: "{{ ansible_user }}"
      changed_when: false
      failed_when: taint_check.rc not in [0, 1]

    - name: Remove control-plane taint to allow workloads
      command: kubectl taint nodes --all node-role.kubernetes.io/control-plane-
      when: taint_check.rc == 0
      become_user: "{{ ansible_user }}"

    - name: Check if Calico is already deployed
      command: kubectl get pods -n kube-system
      register: calico_check
      changed_when: false
      failed_when: false
      become_user: "{{ ansible_user }}"

    - name: Install Calico for Pod Networking if not already present
      command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
      when: "'calico' not in calico_check.stdout"
      become: true
      become_user: "{{ ansible_user }}"

    - name: Check if ArgoCD namespace exists
      stat:
        path: /tmp/argocd_namespace_created
      register: argocd_namespace_check

    - name: Create ArgoCD namespace
      command: kubectl create namespace argocd
      args:
        creates: /tmp/argocd_namespace_created
      become: true
      become_user: "{{ ansible_user }}"
      when: argocd_namespace_check.stat.exists == false

    - name: Check if ArgoCD is already deployed
      command: kubectl get pods -n argocd
      register: argocd_check
      changed_when: false
      failed_when: false
      become_user: "{{ ansible_user }}"

    - name: Install ArgoCD if not already present
      command: kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
      when: "'argocd' not in argocd_check.stdout"
      become: true
      become_user: "{{ ansible_user }}"

    - name: Ensure argo directory exists
      file:
        path: "/tmp/argo"
        state: directory
        mode: '0755'

    - name: Check if ArgoCD Application manifest exists
      stat:
        path: /tmp/argo/manifest.yml
      register: argo_manifest_check

    - name: Create ArgoCD Application manifest
      copy:
        dest: "/tmp/argo/manifest.yml"
        content: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: nginx-test
            namespace: argocd
          spec:
            project: default
            source:
              repoURL: https://github.com/MarkDucommun/azure-kubernetes
              targetRevision: HEAD
              path: argo
            destination:
              server: https://kubernetes.default.svc
              namespace: default
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
        when: argo_manifest_check.stat.exists == false

    - name: Apply ArgoCD Application manifest
      command: kubectl apply -n argocd -f /tmp/argo/manifest.yml
      become: true
      become_user: "{{ ansible_user }}"
