name: Provision Azure Remote Backend

on:
  workflow_dispatch:  # Manual trigger

jobs:
  provision-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZ_CREDENTIALS }}

      - name: Create Resource Group
        run: |
          az group create --name "my-terraform-rg" --location "East US"

      - name: Create Storage Account
        run: |
          az storage account create \
            --name "myterraformstate" \
            --resource-group "my-terraform-rg" \
            --location "East US" \  
            --sku Standard_LRS \
            --kind StorageV2

      - name: Create Storage Container
        run: |
          az storage container create \
            --name "tfstate" \
            --account-name "myterraformstate"
