name: Manual Terraform Deployment

on:
  workflow_dispatch:  # This triggers the workflow manually

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest  # The GitHub Actions runner environment

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Step 2: Set up Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.9.8'  # Specify the version you want
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # Step 3: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 4: Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # Step 5: Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve  # Remove `-auto-approve` if you want manual approval
