name: Test SSH

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  examine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add Private SSH Key
        run: |
          mkdir -p ~/.ssh  # Ensure .ssh directory exists
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github_action_key
          chmod 600 ~/.ssh/github_action_key
          ssh -i ~/.ssh/github_action_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null azureuser@${{secrets.PUBLIC_IP}} "echo 'SSH connection successful'"

      - name: Add Private SSH Key for Ansible
        run: |
          mkdir -p ~/.ssh  # Ensure .ssh directory exists
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github_action_key
          chmod 600 ~/.ssh/github_action_key

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible jq

      - name: Replace Placeholder IP in Inventory
        run: |
          sed -i "s/PLACEHOLDER_IP/${{ secrets.PUBLIC_IP }}/g" ansible/inventory.ini      
          cat ansible/inventory.ini

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/inventory.ini --private-key ~/.ssh/github_action_key ansible/provision_k8s.yml
        env:
          ANSIBLE_PRIVATE_KEY_FILE: ~/.ssh/github_action_key
