name: Test SSH

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  examine:
    runs-on: ubuntu-latest
    steps:
      - name: Add Private SSH Key
        run: |
          mkdir -p ~/.ssh  # Ensure .ssh directory exists
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github_action_key
          chmod 600 ~/.ssh/github_action_key
          ssh -i ~/.ssh/github_action_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null azureuser@${{secrets.PUBLIC_IP}} "echo 'SSH connection successful'"
          
